# Generated by Django 4.2.23 on 2025-08-13 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('document_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('ocr_confidence', models.FloatField(default=0.0)),
                ('ml_confidence', models.FloatField(default=0.0)),
                ('archive_original_path', models.TextField(blank=True, default='')),
                ('archive_ocr_path', models.TextField(blank=True, default='')),
                ('archive_metadata_path', models.TextField(blank=True, default='')),
                ('processing_notes', models.TextField(blank=True, default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.documentcategory')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
    ]
