# Generated by Django 4.2.23 on 2025-08-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('username', models.CharField(blank=True, max_length=150)),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('failures_count', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-attempt_time'],
                'indexes': [models.Index(fields=['ip_address'], name='database_lo_ip_addr_09a455_idx'), models.Index(fields=['username'], name='database_lo_usernam_10af5f_idx'), models.Index(fields=['attempt_time'], name='database_lo_attempt_1446de_idx')],
            },
        ),
    ]
