# Generated by Django 4.2.23 on 2025-08-12 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_loginattempt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginAttempt',
        ),
    ]
