"""
Django settings for webocr project.


Generated by 'django-admin startproject' using Django 5.2.4.


For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/


For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


#File System Paths
from pathlib import Path
# Environment Variable (django-environ)
import environ
# importing OS
import os
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATICFILES_DIRS = [BASE_DIR / 'static']


# set-up environtment
env = environ.Env(DEBUG=(bool, False)) # if we make mistakes it will read as False
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Directory
UPLOAD_FOLDER = BASE_DIR.parent / 'upload'
ARCHIVE_FOLDER = BASE_DIR.parent / 'archive'
DATABASE_FOLDER = BASE_DIR.parent / 'database'


#  OCR Configuration
OPENAI_API_KEY = config('OPENAI_API_KEY', default='')
TESSERACT_CMD = config('TESSERACT_CMD', default='/usr/bin/tesseract')


DOCUMENT_PROCESSING_MAX_RETRIES = 3  # Maximum retry attempts per document
DOCUMENT_PROCESSING_RETRY_DELAY = 2  # Base delay between retries (seconds)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')


ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['.vercel.app', 'localhost', '127.0.0.1'])


INSTALLED_APPS = [
   'django.contrib.admin',
   'django.contrib.auth',
   'django.contrib.contenttypes',
   'django.contrib.sessions',
   'django.contrib.messages',
   'django.contrib.staticfiles',
   'database',
   'rest_framework',
   'csp', # For Content Security Policy
   'core',
   # 'document_processor',
]


MIDDLEWARE = [
   'django.middleware.security.SecurityMiddleware',
   'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files on Vercel
   'django.contrib.sessions.middleware.SessionMiddleware',
   'django.middleware.common.CommonMiddleware',
   'django.middleware.csrf.CsrfViewMiddleware',
   'django.contrib.auth.middleware.AuthenticationMiddleware',
   'core.middleware.SecurityMiddleware',  # Custom security middleware
   'django.contrib.messages.middleware.MessageMiddleware',
   'django.middleware.clickjacking.XFrameOptionsMiddleware',
   'csp.middleware.CSPMiddleware',  # Middleware for Content Security Policy
]


AUTHENTICATION_BACKENDS = [
   'django.contrib.auth.backends.ModelBackend',
]


ROOT_URLCONF = 'webocr.urls'


TEMPLATES = [
   {
       'BACKEND': 'django.template.backends.django.DjangoTemplates',
       'DIRS': [
           BASE_DIR / 'templates',
       ],
       'APP_DIRS': True,
       'OPTIONS': {
           'context_processors': [
               'django.template.context_processors.debug',
               'django.template.context_processors.request',
               'django.contrib.auth.context_processors.auth',
               'django.contrib.messages.context_processors.messages',
               'core.context_processors.chat_history',
           ],
       },
   },
]


WSGI_APPLICATION = 'webocr.wsgi.application'




# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
   'default': env.db() # it read and analyze the db info
}




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
   {
       'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
       'OPTIONS': {
           'max_similarity': 0.7,  # More strict similarity check
       }
   },
   {
       'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
       'OPTIONS': {
           'min_length': env.int('MIN_PASSWORD_LENGTH', default=12),
       }
   },
   {
       'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
   },
   {
       'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
   },
   {
       'NAME': 'core.validators.ComplexityValidator',  # Add your custom validator
   },
]




# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Manila'
USE_I18N = True
USE_TZ = True




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = 'static/'
LOGIN_URL = '/login/'  # Fixed: Added leading slash to prevent relative URL issues




# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'database.User'


# Email configuration for password reset
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('EMAIL_HOST_USER', default='noreply@archivesystem.com')


# For development/testing, you can use console backend instead:
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Cache configuration for rate limiting
CACHES = {
   'default': {
       'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
       'LOCATION': 'unique-snowflake',
   }
}


# Logging configuration
# Enhanced LOGGING configuration - Note: This gets overridden by the main LOGGING config below
# Kept for reference but inactive
LOGGING_SECURITY = {
   'version': 1,
   'disable_existing_loggers': False,
   'formatters': {
       'detailed': {
           'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
           'style': '{',
       },
       'simple': {
           'format': '{levelname} {message}',
           'style': '{',
       },
   },
   'handlers': {
       'console': {
           'level': 'INFO',
           'class': 'logging.StreamHandler',
           'formatter': 'simple',
       },
   },
   'loggers': {
       'security': {
           'handlers': ['console'],
           'level': 'INFO',
           'propagate': False,
       },
       'authentication': {
           'handlers': ['console'],
           'level': 'INFO',
           'propagate': False,
       },
       'database': {
           'handlers': ['console'],
           'level': 'INFO',
           'propagate': True,
       },
   },
}


# Session cookie security
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = env.int('SESSION_COOKIE_AGE', default=3600)  # From .env
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# CSRF cookie security
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'


# Security headers
X_FRAME_OPTIONS = 'DENY' 
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'


# HTTPS enforcement
if not DEBUG:
   SECURE_SSL_REDIRECT = True
   SECURE_HSTS_SECONDS = 31536000
   SECURE_HSTS_INCLUDE_SUBDOMAINS = True
   SECURE_HSTS_PRELOAD = True
   SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
  
   SESSION_COOKIE_SECURE = True
   CSRF_COOKIE_SECURE = True


# Content Security Policy (CSP) settings using django-csp variables
# Allow CDN styles and fonts used by Tailwind and Font Awesome
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net", "https://cdnjs.cloudflare.com")
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net", "https://cdnjs.cloudflare.com")
CSP_IMG_SRC = ("'self'", "data:", "https:")
CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com", "https://cdnjs.cloudflare.com")
CSP_CONNECT_SRC = ("'self'",)


# Domain name
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://arkayb.vercel.app',
    'https://*.vercel.app'
])


# Model Configuration
LLM_MODEL_NAME = os.environ.get('LLM_MODEL_NAME', 'Qwen/Qwen2-VL-7B-Instruct')
LLM_MAX_TOKENS = int(os.environ.get('LLM_MAX_TOKENS', '256'))
LLM_DEFAULT_TEMPERATURE = float(os.environ.get('LLM_DEFAULT_TEMPERATURE', '0.2'))


# Development/Production Toggle
USE_MOCK_LLM = os.environ.get('USE_MOCK_LLM', 'False').lower() == 'true'


# Search Configuration
MAX_CONTEXT_DOCUMENTS = int(os.environ.get('MAX_CONTEXT_DOCUMENTS', '5'))
MAX_CONTEXT_LENGTH = int(os.environ.get('MAX_CONTEXT_LENGTH', '2000'))


# ====================================
# PERFORMANCE & CACHING
# ====================================


# Cache configuration for LLM model loading
CACHES = {
   'default': {
       'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
       'LOCATION': 'llm-cache',
       'TIMEOUT': 3600,  # 1 hour
       'OPTIONS': {
           'MAX_ENTRIES': 1000,
       }
   }
}


# ====================================
# LOGGING CONFIGURATION
# ====================================

# Base logging configuration
LOGGING = {
   'version': 1,
   'disable_existing_loggers': False,
   'formatters': {
       'verbose': {
           'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
           'style': '{',
       },
       'simple': {
           'format': '{levelname} {message}',
           'style': '{',
       },
   },
   'handlers': {
       'console': {
           'level': 'DEBUG' if DEBUG else 'INFO',
           'class': 'logging.StreamHandler',
           'formatter': 'simple',
       },
   },
   'loggers': {
       'django': {
           'handlers': ['console'],
           'level': 'INFO',
           'propagate': True,
       },
       'core.services.llm_search': {
           'handlers': ['console'],
           'level': 'DEBUG' if DEBUG else 'INFO',
           'propagate': True,
       },
   },
}

# Only add file logging in development (local environment with writable filesystem)
if DEBUG:
    # Create logs directory if it doesn't exist
    LOGS_DIR = os.path.join(BASE_DIR, 'logs')
    os.makedirs(LOGS_DIR, exist_ok=True)
    
    # Add file handler for local development
    LOGGING['handlers']['file'] = {
        'level': 'INFO',
        'class': 'logging.FileHandler',
        'filename': 'logs/search.log',
        'formatter': 'verbose',
    }
    LOGGING['loggers']['django']['handlers'].append('file')
    LOGGING['loggers']['core.services.llm_search']['handlers'].append('file')


# ====================================
# SECURITY ENHANCEMENTS
# ====================================


# Rate limiting for LLM requests (if you're using django-ratelimit)
RATELIMIT_ENABLE = True
RATELIMIT_USE_CACHE = 'default'


# ====================================
# ENVIRONMENT-SPECIFIC CONFIGURATIONS
# ====================================


# For Development
if DEBUG:
   # Use smaller model for development - 1.5B is perfect for RTX 2050 + 7GB RAM
   LLM_MODEL_NAME = 'Qwen/Qwen2-1.5B-Instruct'  # Smaller model (3-4GB VRAM, fast)
   # Alternative: 'Qwen/Qwen2-7B-Instruct' requires 12GB+ (too heavy for your device)
   USE_MOCK_LLM = False  # Enable real LLM with 1.5B model
  
   # Enable more verbose logging
   LOGGING['loggers']['core.services.llm_search']['level'] = 'DEBUG'


# For Production 
else:
   # Use full model in production
   USE_MOCK_LLM = False
  
   # Production-specific optimizations
   LLM_MAX_TOKENS = 512  # Allow longer responses in production
  
   # Additional security headers
   SECURE_BROWSER_XSS_FILTER = True
   SECURE_CONTENT_TYPE_NOSNIFF = True
   X_FRAME_OPTIONS = 'DENY'




# ====================================
# STATIC FILES UPDATE
# ====================================


# Make sure static files are properly configured for the new search interface
STATIC_URL = '/static/'
STATICFILES_DIRS = [
   BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for Vercel
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    # Use non-manifest storage to avoid runtime errors when collectstatic output
    # is not packaged into the serverless function on Vercel.
    # This still serves compressed static files via WhiteNoise.
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}


# ====================================
# TEMPLATE UPDATE
# ====================================


# Make sure your templates can find the new search templates
TEMPLATES = [
   {
       'BACKEND': 'django.template.backends.django.DjangoTemplates',
       'DIRS': [
           BASE_DIR / 'templates',  # Make sure this is set correctly
       ],
       'APP_DIRS': True,
       'OPTIONS': {
           'context_processors': [
               'django.template.context_processors.debug',
               'django.template.context_processors.request',
               'django.contrib.auth.context_processors.auth',
               'django.contrib.messages.context_processors.messages',
           ],
       },
   },
]

# ====================================
# FUZZY SEARCH CONFIGURATION
# ====================================

# Enable/disable fuzzy search
ENABLE_FUZZY_SEARCH = os.environ.get('ENABLE_FUZZY_SEARCH', 'True').lower() == 'true'

# Minimum similarity score for fuzzy matches (0-100)
# 85 = Very strict, high precision (recommended for production)
# 80 = Strict, fewer false positives
# 70 = Balanced
# 60 = Lenient, more potential matches
FUZZY_SEARCH_THRESHOLD = int(os.environ.get('FUZZY_SEARCH_THRESHOLD', '80'))

# Maximum number of fuzzy results per search stage
FUZZY_SEARCH_LIMIT = int(os.environ.get('FUZZY_SEARCH_LIMIT', '10'))

# Fuzzy search algorithms priority (rapidfuzz options)
FUZZY_ALGORITHMS = {
    'partial_ratio': True,      # Good for substring matching
    'token_sort_ratio': True,   # Good for word order variations
    'token_set_ratio': True,    # Good for missing/extra words
    'ratio': False             # Basic similarity (usually too strict)
}

# Performance settings
FUZZY_CHUNK_SIZE = int(os.environ.get('FUZZY_CHUNK_SIZE', '200'))  # Words per chunk for OCR fuzzy search
FUZZY_MAX_TEXT_LENGTH = int(os.environ.get('FUZZY_MAX_TEXT_LENGTH', '5000'))  # Max chars to analyze per document

# Development settings
if DEBUG:
    # Use production settings for consistent results
    FUZZY_SEARCH_THRESHOLD = 80  # Strict matching for accuracy
    FUZZY_SEARCH_LIMIT = 10


