# Generated by Django 4.2.23 on 2025-08-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('username', models.CharField(blank=True, max_length=150)),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('failures_count', models.IntegerField(default=1)),
            ],
            options={
                'unique_together': {('ip_address', 'username')},
            },
        ),
    ]
