# Generated by Django 4.2.23 on 2025-08-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usersession_suspiciousactivity_securityevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suspiciousactivity',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Suspicious Activity', 'verbose_name_plural': 'Suspicious Activities'},
        ),
    ]
