# Generated by Django 4.2.27 on 2026-01-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0005_delete_loginattempt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-upload_date"],
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
        migrations.RenameIndex(
            model_name="document",
            new_name="idx_client_name",
            old_name="database_do_client__459205_idx",
        ),
        migrations.RenameIndex(
            model_name="document",
            new_name="idx_status",
            old_name="database_do_status_250f1c_idx",
        ),
        migrations.RenameIndex(
            model_name="document",
            new_name="idx_upload_date",
            old_name="database_do_upload__dd9649_idx",
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["document_name"], name="idx_document_name"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["client_name", "status"], name="idx_client_status"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["client_name", "upload_date"], name="idx_client_date"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["status", "upload_date"], name="idx_status_date"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["client_name", "document_name"], name="idx_client_doc"
            ),
        ),
    ]
