# Generated by Django 4.2.23 on 2025-07-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='search_log',
            options={'ordering': ['-search_at']},
        ),
        migrations.AddIndex(
            model_name='document_metadata',
            index=models.Index(fields=['amount'], name='database_do_amount_58c2a9_idx'),
        ),
        migrations.AddIndex(
            model_name='document_metadata',
            index=models.Index(fields=['currency'], name='database_do_currenc_9fe182_idx'),
        ),
        migrations.AddIndex(
            model_name='document_metadata',
            index=models.Index(fields=['date_issued'], name='database_do_date_is_973f69_idx'),
        ),
        migrations.AddIndex(
            model_name='document_metadata',
            index=models.Index(fields=['client_name'], name='database_do_client__4f28b5_idx'),
        ),
        migrations.AddIndex(
            model_name='document_metadata',
            index=models.Index(fields=['vendor_name'], name='database_do_vendor__01c28a_idx'),
        ),
        migrations.AddIndex(
            model_name='document_metadata',
            index=models.Index(fields=['invoice_number'], name='database_do_invoice_f3c776_idx'),
        ),
    ]
