# Generated by Django 4.2.23 on 2025-08-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_documents_options_alter_search_log_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='status',
            field=models.CharField(choices=[('updated', 'Updated'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='updated', max_length=15),
        ),
    ]
