# Generated by Django 4.2.23 on 2025-08-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_loginattempt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginAttempt',
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['client_name'], name='database_do_client__459205_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='database_do_status_250f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['upload_date'], name='database_do_upload__dd9649_idx'),
        ),
    ]
